export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SAVE_EMAIL = "SAVE_EMAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";

export const SAVE_DRIVER_INFO = "SAVE_DRIVER_INFO";


export const SAVE_VEHICLE_INFO = "SAVE_VEHICLE_INFO";