docker_image: &docker_image
  working_directory: ~/seeker-web-client
  docker:
  - image: circleci/node:14.17.4

restore_cache:
- &restore_cache
  restore_cache:
    keys:
    - v1-dependencies-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

deploy: &deploy 
  docker:
    - image: google/cloud-sdk
  steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Authenticate service account
        command: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
    - run: 
        name: 'Change service to deploy'
        command: sed 's/qa/'$GOOGLE_SERVICE'/g' app-example.yaml > app.yaml && cat app.yaml
    - run: 
        name: 'Deploy app'
        command: gcloud app deploy

build: &build
  <<: *docker_image
  steps:
    - checkout
    - *restore_cache
    - run: npm run build:dev
    - persist_to_workspace:
        root: .
        paths: build

version: 2
jobs:
  install_dependencies:
    <<: *docker_image
    steps:
    - checkout
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

  build-dev:
    <<: *build

  deploy-dev: 
    <<: *deploy
  
workflows:
  version: 2
  continuos_integration:
    jobs:
      - install_dependencies
      - build-dev:
          requires:
            - install_dependencies
          context: seekr-qa
          filters:
            branches:
              only: 
                - dev
      - deploy-dev: 
          requires: 
            - build-qa
          context: seekr-qa
          filters:
            branches:
              only: 
                - dev
